learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='sai'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(r):
    context_dict={'text':'hello world','number':100}
    return render(r,'basic_app/index.html',context_dict)

def other(r):
    return render(r,'basic_app/other.html')

def relative(r):
    return render(r,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{%url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
          <li><a class="navbar-link" href="{%url 'sai:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {%block body_block%}


      {%endblock%}

      <!-- <h1>YOU ARE IN BASE PAGE</h1> -->
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{%load templates%}
{%extends "basic_app/base.html"%}
  {%block body_block%}
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>INDEX</title>
  </head>
  <body> -->
    <h1>YOU ARE IN INDEX PAGE</h1>
    <h2>{{text |cut:'world'}}</h2>
    <h2>{{number|add:'99'}}</h2>
  {%endblock%}
  <!-- </body>
</html> -->

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{%extends "basic_app/base.html"%}
  {%block body_block%}
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>OTHER</title>
  </head>
  <body> -->
    <h1>YOU ARE IN OTHER PAGE</h1>
    <h2>This is an example of inheritance</h2>
    {%endblock%}
  <!-- </body>
</html> -->

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE</title>
  </head>
  <body>
    <h1>YOU ARE IN RELATIVE URL PAGE</h1>
    <a href="{%url 'sai:other'%}">Click here to Other</a>
    <a href="{%url 'admin:index' %}">Admin Page</a>
    <a href="{%url 'index'%}">Index</a>
  </body>
</html>